Add did method web
digitalbazaar/bedrock-did-io pull request #20
Opened 2024-01-23 18:06 UTC by aljones15

2024-01-23 20:39 UTC, davidlehn commented on package.json
> +    "@digitalbazaar/did-method-web": "^1.0.0",
sort deps

2024-01-23 21:23 UTC, dlongley requested changes

2024-01-23 21:23 UTC, dlongley commented on lib/index.js
> +  const didKeyDriver = didMethodKey.driver(cfg.methods.key);
These options don't work that way:

https://github.com/digitalbazaar/did-method-key/blob/main/lib/index.js#L12

The are instead used below.

The `didMethodWeb` driver should do the same thing with the same options, I believe. However, there are additional options for the `did:web` driver like the `fetchOptions` and `allowList` that would be passed to the driver constructor. So a little more work is needed below to split these config options up for the `did:web` driver and to do the right thing.

2024-01-24 16:14 UTC, aljones15 commented on package.json
> +    "@digitalbazaar/did-method-web": "^1.0.0",
sorted deps alphabetically here: https://github.com/digitalbazaar/bedrock-did-io/pull/20/commits/101c82fa11ef1fbcc687515588cb72719f2a5ba3

2024-04-14 22:53 UTC, dlongley approved these changes

2024-04-14 23:18 UTC, merged